sudo: required
language: node_js
node_js:
- node
services:
- docker
before_install:
- sudo service postgresql stop
- node --version
- gulp create-version-sha
- cat version.sha
- npm install -g gulp
- docker-compose up -d
- docker ps -a
before_script:
- gulp selenium-install
- gulp create-pace-db
script:
    - "./run_all_tests.sh"
after_success:
- openssl aes-256-cbc -K $encrypted_53ec6a2573a1_key -iv $encrypted_53ec6a2573a1_iv
  -in do_deploy.enc -out do_deploy -d
- chmod 600 do_deploy
- ".travis/deploy.sh"
